=== Javier-G-1/prog-reto2/exportaciones/general.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">

  <xs:element name="federacionBalonmano">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="temporadas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="temporada" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="equipos">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="equipo" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="ganados" type="xs:nonNegativeInteger"/>
                                <xs:element name="perdidos" type="xs:nonNegativeInteger"/>
                                <xs:element name="empatados" type="xs:nonNegativeInteger"/>
                                <xs:element name="golesFavor" type="xs:nonNegativeInteger"/>
                                <xs:element name="golesContra" type="xs:nonNegativeInteger"/>
                                <xs:element name="jugadores">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="jugador" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="nombre" type="xs:string"/>
                                            <xs:element name="nacionalidad" type="xs:string" minOccurs="0"/>
                                            <xs:element name="altura" type="xs:string" minOccurs="0"/>
                                            <xs:element name="peso" type="xs:string" minOccurs="0"/>
                                            <xs:element name="dorsal" type="xs:nonNegativeInteger" minOccurs="0"/>
                                            <xs:element name="posicion" type="xs:string" minOccurs="0"/>
                                            <xs:element name="foto" minOccurs="0">
                                              <xs:complexType>
                                                <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute name="id" type="xs:string" use="required"/>
                                          <xs:attribute name="equipo" type="xs:string" use="required"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="escudo" minOccurs="0">
                                  <xs:complexType>
                                    <xs:attribute name="url" type="xs:anyURI" use="optional"/>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="jornadas" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="jornada" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="partidos">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="partido" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="golesLocal" type="xs:nonNegativeInteger"/>
                                            <xs:element name="golesVisitante" type="xs:nonNegativeInteger"/>
                                            <xs:element name="estado" type="xs:string"/>
                                          </xs:sequence>
                                          <xs:attribute name="id" type="xs:string" use="required"/>
                                          <xs:attribute name="local" type="xs:string" use="required"/>
                                          <xs:attribute name="visitante" type="xs:string" use="required"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Javier-G-1/prog-reto2/federacion_Temporada_2025_26.xml
<?xml version="1.0" encoding="UTF-8"?>
<federacionBalonmano xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="general.xsd">

    <temporadas>
        <temporada id="2025_2026">
            <equipos>
                <equipo id="E001">
                    <nombre>Granada</nombre>
                    <ganados>5</ganados>
                    <perdidos>5</perdidos>
                    <empatados>0</empatados>
                    <golesFavor>236</golesFavor>
                    <golesContra>161</golesContra>
                    <jugadores>
                        <jugador id="JU001" equipo="E001">
                            <nombre>Carlos Muñoz</nombre>
                            <nacionalidad>BOLIVIA</nacionalidad>
                            <altura>220 cm</altura>
                            <peso>50 kg</peso>
                            <dorsal>13</dorsal>
                            <posicion>Pivote</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU002" equipo="E001">
                            <nombre>Marta Domínguez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU003" equipo="E001">
                            <nombre>Andrés Cortés</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU004" equipo="E001">
                            <nombre>Lucía Palacios</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                    </jugadores>
                    <escudo url=""/>
                </equipo>
                <equipo id="E002">
                    <nombre>Sevilla</nombre>
                    <ganados>6</ganados>
                    <perdidos>3</perdidos>
                    <empatados>1</empatados>
                    <golesFavor>223</golesFavor>
                    <golesContra>187</golesContra>
                    <jugadores>
                        <jugador id="JU001" equipo="E002">
                            <nombre>Marina Torres</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU002" equipo="E002">
                            <nombre>Fernando Vázquez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU003" equipo="E002">
                            <nombre>Ana Beltrán</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU004" equipo="E002">
                            <nombre>Rubén Márquez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                    </jugadores>
                    <escudo url=""/>
                </equipo>
                <equipo id="E003">
                    <nombre>Zaragoza</nombre>
                    <ganados>5</ganados>
                    <perdidos>5</perdidos>
                    <empatados>0</empatados>
                    <golesFavor>266</golesFavor>
                    <golesContra>278</golesContra>
                    <jugadores>
                        <jugador id="JU001" equipo="E003">
                            <nombre>Miguel Ortega</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU002" equipo="E003">
                            <nombre>Claudia Rivas</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU003" equipo="E003">
                            <nombre>Javier Torres</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU004" equipo="E003">
                            <nombre>Isabel Salinas</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                    </jugadores>
                    <escudo url=""/>
                </equipo>
                <equipo id="E004">
                    <nombre>Valencia</nombre>
                    <ganados>4</ganados>
                    <perdidos>6</perdidos>
                    <empatados>0</empatados>
                    <golesFavor>211</golesFavor>
                    <golesContra>263</golesContra>
                    <jugadores>
                        <jugador id="JU001" equipo="E004">
                            <nombre>Raúl Pérez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU002" equipo="E004">
                            <nombre>Andrea Delgado</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU003" equipo="E004">
                            <nombre>Luis Navarro</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                        <jugador id="JU004" equipo="E004">
                            <nombre>Marta Ramírez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
                            <peso>75kg</peso>
                            <dorsal>0</dorsal>
                            <posicion>Posición</posicion>
                            <foto url=""/>
                        </jugador>
                    </jugadores>
                    <escudo url=""/>
                </equipo>
                <equipo id="E005">
                    <nombre>Athletic Club</nombre>
                    <ganados>5</ganados>
                    <perdidos>5</perdidos>
                    <empatados>0</empatados>
                    <golesFavor>217</golesFavor>
                    <golesContra>232</golesContra>
                    <jugadores>
                        <jugador id="JU001" equipo="E005">
                            <nombre>Pablo Martínez</nombre>
                            <nacionalidad>España</nacionalidad>
                            <altura>175cm</altura>
